---
# tasks file for vector_role
- name: Download Vector from remote URL
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-{{ vec_arc_var }}-unknown-linux-musl.tar.gz"
    dest: "/tmp/vector-{{ vector_version }}-{{ vec_arc_var }}-unknown-linux-musl.tar.gz"
    mode: 0755
    timeout: 60
    force: true
    validate_certs: false
  register: get_vector
  until: get_vector is succeeded
  tags: vector
- name: Create directrory for vector
  ansible.builtin.file:
    state: directory
    path: "{{ vector_home }}"
    mode: 0755
  tags: vector
- name: Extract Vector in the installation directory
  ansible.builtin.unarchive:
    copy: false
    src: "/tmp/vector-{{ vector_version }}-{{ vec_arc_var }}-unknown-linux-musl.tar.gz"
    dest: "{{ vector_home }}"
    extra_opts: [--strip-components=2]
    creates: "{{ vector_home }}/bin/vector"
  tags: vector
- name: Set environment Vector
  ansible.builtin.template:
    src: templates/vector.toml
    dest: "{{ vector_home }}/vector.toml"
    mode: 0755
  tags: vector